### ISSUE TITLE
Configuring Routes

### ISSUE THREAD

**Issue by tacman** [craue/CraueFormFlowDemoBundle#7]
PROJECT_DIR=flow-bundle-demo && symfony new --full $PROJECT_DIR && cd $PROJECT_DIR
composer require craue/formflow-demo-bundle
bin/console debug:route

At this point, there's no routes to the demo.  The previous solution was to include the following in routes.yaml

```yaml
# routes.yaml
CraueFormFlowDemoBundle:
  resource: '@CraueFormFlowDemoBundle/Controller/'
  type: annotation
```

    bin/console c:c

  [InvalidArgumentException]                                                                                                                                     
  Bundle "CraueFormFlowDemoBundle" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your App\Kernel.php file?  

I'm hacking away trying to figure out how to register the bundle, since the underlying blocks to build the form are all using that namespace.

Thanks.
